openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/posts:
    post:
      summary: 'Create A New Post'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  message: 'Post Created Successfully!'
                  code: 201
                  data:
                    platform_id: '1'
                    title: quod
                    description: qui
                    status: true
                    updated_at: '2021-11-11T21:01:46.000000Z'
                    created_at: '2021-11-11T21:01:46.000000Z'
                    id: 8
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 'Post Created Successfully!'
                  code:
                    type: integer
                    example: 201
                  data:
                    type: object
                    example:
                      platform_id: '1'
                      title: quod
                      description: qui
                      status: true
                      updated_at: '2021-11-11T21:01:46.000000Z'
                      created_at: '2021-11-11T21:01:46.000000Z'
                      id: 8
      tags:
        - Posts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                platform_id:
                  type: integer
                  description: 'Platform ID. Example : 1'
                  example: 12
                title:
                  type: string
                  description: 'Title Of The Post. Example : Post Title'
                  example: qui
                description:
                  type: string
                  description: 'Post Description . Example : Post Description'
                  example: quia
                status:
                  type: boolean
                  description: 'Status . Example : 1'
                  example: true
              required:
                - platform_id
                - description
                - status
      security: []
  /api/subscribers:
    post:
      summary: 'Subscribe to a Platform'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  message: 'Subscribed Successfully!'
                  code: 201
                  data:
                    email: send2raju.bd@gmail.com
                    platform_id: '1'
                    status: true
                    updated_at: '2021-11-11T21:05:37.000000Z'
                    created_at: '2021-11-11T21:05:37.000000Z'
                    id: 4
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 'Subscribed Successfully!'
                  code:
                    type: integer
                    example: 201
                  data:
                    type: object
                    example:
                      email: send2raju.bd@gmail.com
                      platform_id: '1'
                      status: true
                      updated_at: '2021-11-11T21:05:37.000000Z'
                      created_at: '2021-11-11T21:05:37.000000Z'
                      id: 4
      tags:
        - Subscriptions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                platform_id:
                  type: integer
                  description: 'Platform ID. Example : 1'
                  example: 16
                email:
                  type: email
                  description: 'Title Of The Post. Example : send2raju.bd@gmail.com'
                  example: nisi
                status:
                  type: boolean
                  description: 'Status . Example : 1'
                  example: true
              required:
                - platform_id
                - status
      security: []
tags:
  -
    name: Posts
    description: ''
  -
    name: Subscriptions
    description: ''
