openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/subscribers:
    post:
      summary: 'Subscribe to a Platform'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  message: 'Subscribed Successfully!'
                  code: 201
                  data: []
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 'Subscribed Successfully!'
                  code:
                    type: integer
                    example: 201
                  data:
                    type: array
                    example: []
      tags:
        - Subscriptions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                platform_id:
                  type: integer
                  description: 'Platform ID. Example : 1'
                  example: 12
                email:
                  type: email
                  description: 'Title Of The Post. Example : send2raju.bd@gmail.com'
                  example: doloremque
                status:
                  type: boolean
                  description: 'Status . Example : 1'
                  example: true
              required:
                - platform_id
                - status
      security: []
  /api/posts:
    post:
      summary: 'Create A New Post'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  message: 'Post Created Successfully!'
                  code: 201
                  data: []
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 'Post Created Successfully!'
                  code:
                    type: integer
                    example: 201
                  data:
                    type: array
                    example: []
      tags:
        - Posts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                platform_id:
                  type: integer
                  description: 'Platform ID. Example : 1'
                  example: 7
                title:
                  type: string
                  description: 'Title Of The Post. Example : Post Title'
                  example: quod
                description:
                  type: string
                  description: 'Post Description . Example : Post Description'
                  example: qui
                status:
                  type: boolean
                  description: 'Status . Example : 1'
                  example: true
              required:
                - platform_id
                - description
                - status
      security: []
tags:
  -
    name: Subscriptions
    description: ''
  -
    name: Posts
    description: ''
